id: PAD3F7994
initial_creation_type: input
source_metadata:
  title: Siddhāntabindu
  language:
  - English
  - Sanskrit
  term: Sanskrit -- Śāstra -- Philosophy -- Vedānta
  data entry: Takahiro Kato
  contribution to GRETIL: Takahiro Kato
  initial normalization and conversion to legacy GRETIL formats: Reinhold Grünendahl
  normalization and conversion to TEI-conformant markup: Maximilian Mehner
created_at: '2022-03-09T14:55:27.900643'
last_modified_at: '2022-03-09T14:55:27.900657'
